FROM maven:3-jdk-8-alpine AS build

WORKDIR /opt/app

COPY ./ /opt/app/

RUN mvn clean install -DskipTests

FROM westerlytutors/hello-springboot-tomcat:latest
COPY --from=build /opt/app/target/*.war /usr/local/tomcat/webapps
CMD ["catalina.sh", "run"]
