/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    stages {
        stage('Checkout') {
            steps {
                sh '''
                    cleanWs()
                    checkout scm
                '''
            }
        }
        stage('Unit Test') {
            steps {
                sh '''
                    cd maven-docker-pipeline
                    mvn test
                '''
            }
        }
        stage('Package') {
            steps {
                sh '''
                    cd maven-docker-pipeline
                    mvn package
                '''
            }
        }
    }
}
