/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    stages {
        stage('Unit Test') {
            steps {
                sh '''
                    cd maven-docker-pipeline
                    mvn clean
                    mvn test
                    mvn package
                '''
            }
        }
    }
}
