/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    stages {
                stage ('Initialize') {
                    steps {
                        sh '''
                            echo "Compiling Maven Project"
                            cd maven-pipeline
                            mvn compile
                        '''
                    }
                }
                stage ('Package') {
                    steps {
                        sh '''
                            echo "Packaging Maven Project"
                            mvn package
                        '''
                    }
                }
    }
}
